workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      node: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Give permission to gradlew
        script: |
          cd android
          chmod +x gradlew
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - karanrana3095@gmail.com
